[target.aarch64-unknown-linux-gnu]
linker = "C:/ToolChains/aarch64/bin/aarch64-none-linux-gnu-gcc.exe"

[target.armv7-unknown-linux-gnueabihf]
linker = "C:/ToolChains/arm32/bin/arm-none-linux-gnueabihf-gcc.exe"
